### ISSUE TITLE
Base table or view not found: 1146 Table 'pos.settings'

### ISSUE THREAD

**Issue by omarabdallah96** [tomatophp/filament-pos#2]
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'pos.settings' doesn't exist (Connection: mysql, SQL: select `payload` from `settings` where `name` = site_currency limit 1)

**Comment by fadymondy** [comment]
we need the Media Library plugin to be installed and migrated you can use this command to publish the migration

```bash
php artisan vendor:publish --provider="Spatie\MediaLibrary\MediaLibraryServiceProvider" --tag="medialibrary-migrations"
```

now you need to install the settings hub use these commands

```bash
php artisan vendor:publish --provider="Spatie\LaravelSettings\LaravelSettingsServiceProvider" --tag="migrations"
php artisan filament-settings-hub:install
```

I update the docs about that
