### ISSUE TITLE
Class "TomatoPHP\FilamentAccounts\Filament\Resources\AccountResource\Pages\AccountPages" not found

### ISSUE THREAD

**Issue by brianalviano** [tomatophp/filament-pos#3]
at vendor/tomatophp/filament-accounts/src/Filament/Resources/AccountResource.php:80
     76▕     }
     77▕ 
     78▕     public static function getPages(): array
     79▕     {
  ➜  80▕         return config('filament-accounts.accounts.pages') ? config('filament-accounts.accounts.pages')::routes() : [
     81▕             'index' => \TomatoPHP\FilamentAccounts\Filament\Resources\AccountResource\Pages\ListAccounts::route('/'),
     82▕             'edit' => \TomatoPHP\FilamentAccounts\Filament\Resources\AccountResource\Pages\EditAccount::route('/{record}/edit')
     83▕         ];
     84▕     }

![image](https://github.com/user-attachments/assets/49cb40a2-5da7-40f4-83a8-a0f07000be36)

**Comment by himadreekuntal** [comment]
facing the same issue.

**Comment by fadymondy** [comment]
fixed in the last version.
