### ISSUE TITLE
Database migration error for fresh install

### ISSUE THREAD

**Issue by huiyang** [tomatophp/filament-pos#5]
Thanks for the plugin, but i getting this error when trying to install tomatophp filament pos plugin.

SQLSTATE[HY000]: General error: 1824 Failed to open the referenced table 'teams' (Connection: mysql, SQL: alter table `products` add constraint `products_team_id_foreign` foreign key (`team_id`) references `teams` (`id`) on delete set null)

Thanks.

**Comment by fadymondy** [comment]
fixed on last version of filament-e-commerce plugin thanks for your report
