### ISSUE TITLE
Cannot add foreign key constraint `categories_team_id_foreign`

### ISSUE THREAD

**Issue by soofdev** [tomatophp/filament-pos#6]
I followed the instructions. When the migrations get to 2024_09_18_150652_add_team_id_to_categories_table I get this error:

 SQLSTATE[HY000]: General error: 1215 Cannot add foreign key constraint (Connection: mysql, SQL: alter table `categories` add constraint `categories_team_id_foreign` foreign key (`team_id`) references `teams` (`id`) on delete cascade)

<img width="823" alt="Screenshot 2024-09-29 at 8 30 40 PM" src="https://github.com/user-attachments/assets/c399c38e-007a-439c-9f9f-5f863c700e73">

**Comment by soofdev** [comment]
> [TOT-98 Cannot add foreign key constraint `categories_team_id_foreign`](https://linear.app/tomatophp/issue/TOT-98/cannot-add-foreign-key-constraint-categories-team-id-foreign)

I can't access this on Linear.

**Comment by fadymondy** [comment]
@soofdev it's okay it's just for the support team thanks for your report.

**Comment by fadymondy** [comment]
It's fixed on the last version of CMS. Please update it.
